// src/render/Notification/Ingredients/index.tsx
import { NSpace } from 'naive-ui'

import type { TIngredientsItem } from '@/material'

import TagItem from '@/components/common/tags/index.vue'

import { renderNotificationTitle } from '@/render/Notification/CommonTitle'

export function createNotification (item: TIngredientsItem) {
  const { ingredient_tags, from } = item
  const [ gather, buy ] = from
  return {
    title: renderNotificationTitle(item, { type: 'ingredients' }),
    meta: () => {
      return <NSpace vertical>
        <>{ gather }</>
        <>{ buy }</>
      </NSpace>
    },
    content: () => {
      return (
        <NSpace>
          { ingredient_tags.map((item) => <TagItem category="like" value={item} />) }
        </NSpace>
      )
    },
  }
}

// src/view/ingredients/index.vue
<script setup lang="ts">
import { createDiscreteApi } from 'naive-ui'

import { useIngredientsStore } from '@/pinia'

import type { TIngredientsItem } from '@/material'

import SpriteItem from '@/components/common/sprite/index.vue'

import { createNotification } from '@/render/Notification/Ingredients'

const ingredientsStore = useIngredientsStore()

const { ingredients } = ingredientsStore

const { notification } = createDiscreteApi(['notification'])

const handleItemClick = (item: TIngredientsItem) => {
  const options = createNotification(item)
  notification.create(options)
}
</script>

<template>
  <!-- page -->
  <div class="recipes-page pd12">
    <!-- card -->
    <n-card>
      <!-- content -->
      <ul class="material-list">
        <li
          class="item"
          v-for="(item, index) in ingredients"
          :key="index"
          @click="handleItemClick(item)"
        >
          <!-- icon -->
          <SpriteItem :index="item.index" type="ingredients" :size="64" :value="item.name" :title="item.name" />
          <!-- text -->
          <span class="label">{{ item.name }}</span>
        </li>
      </ul>
    </n-card>
  </div>
</template>

<style scoped lang="scss">
@import url('@/styles/material.scss');
</style>
