// src/view/beverages/index.vue
<script setup lang="ts">
import { createDiscreteApi } from 'naive-ui'

import { useBeveragesStore } from '@/pinia'

import type { TBeverageItem } from '@/material'

import SpriteItem from '@/components/common/sprite/index.vue'

import { createNotification } from '@/render/Notification/Beverages'

const beveragesStore = useBeveragesStore()

const { beverages } = beveragesStore

const { notification } = createDiscreteApi(['notification'])

const handleItemClick = (item: TBeverageItem) => {
  const options = createNotification(item)
  notification.create(options)
}
</script>

<template>
  <!-- page -->
  <div class="beverages-page pd12">
    <!-- card -->
    <n-card>
      <!-- content -->
      <ul class="material-list">
        <li
          class="item"
          v-for="(item, index) in beverages"
          :key="index"
          @click="handleItemClick(item)"
        >
          <!-- icon -->
          <n-badge type="success" :value="item.price">
            <SpriteItem :index="item.index" type="beverages" :size="64" :value="item.name" :title="item.name" />
          </n-badge>
          <!-- text -->
          <span class="label">{{ item.name }}</span>
        </li>
      </ul>
    </n-card>
  </div>
</template>

<style scoped lang="scss">
@import url('@/styles/material.scss');
</style>

// src/render/Notification/Beverages/index.tsx
import { NSpace } from 'naive-ui'

import type { TBeverageItem } from '@/material'

import TagItem from '@/components/common/tags/index.vue'

import { renderNotificationTitle } from '@/render/Notification/CommonTitle'

export function createNotification (item: TBeverageItem) {
  const { beverage_tags, from, price, level } = item
  return {
    title: renderNotificationTitle(item, { type: 'beverages' }),
    description: () => {
      return (
        <NSpace>
          <span>售价 : ${price}</span>
          <span>等级 : Lv.{level}</span>
        </NSpace>
      )
    },
    meta: () => {
      return <NSpace vertical>
        { from.map(v => v) }
      </NSpace>
    },
    content: () => {
      return (
        <NSpace>
          { beverage_tags.map((item) => <TagItem category="beverage" value={item} />) }
        </NSpace>
      )
    },
  }
}
